# Generated by Django 4.2.5 on 2023-10-18 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.SmallIntegerField(null=True)),
                ('major', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('classCodeId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='class_review.classcodes')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledStudentClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='class_review.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photoURL', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campusCode', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.SmallIntegerField()),
                ('comment', models.TextField(null=True)),
                ('studentClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_review.enrolledstudentclasses')),
            ],
        ),
        migrations.AddField(
            model_name='enrolledstudentclasses',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_review.students'),
        ),
        migrations.AddField(
            model_name='classes',
            name='professorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='class_review.professors'),
        ),
    ]
