# Generated by Django 4.2.5 on 2023-10-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='label',
            field=models.CharField(default='-', max_length=250),
            preserve_default=False,
        ),
    ]
