# Generated by Django 4.2.5 on 2023-10-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_review', '0002_classes_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcodes',
            name='code',
            field=models.CharField(default='-', max_length=250),
            preserve_default=False,
        ),
    ]
